insert into Artist (artistID, name, biography, style, totalExhibitions) values (1, 'Lesli d''Arcy', 'Pablo Picasso', 'impressionism', 8);
insert into Artist (artistID, name, biography, style, totalExhibitions) values (2, 'Dorita Vanin', 'Leonardo da Vinci', 'abstract', 68);
insert into Artist (artistID, name, biography, style, totalExhibitions) values (3, 'Lawry Grist', 'Pablo Picasso', 'abstract', 97);
insert into Artist (artistID, name, biography, style, totalExhibitions) values (4, 'Brnaba Gruszczak', 'Michelangelo', 'abstract', 92);
insert into Artist (artistID, name, biography, style, totalExhibitions) values (5, 'Krystle Swanborough', 'Frida Kahlo', 'impressionism', 72);
insert into Artist (artistID, name, biography, style, totalExhibitions) values (6, 'Bronnie Boater', 'Michelangelo', 'realism', 62);
insert into Artist (artistID, name, biography, style, totalExhibitions) values (7, 'Xylina Baine', 'Leonardo da Vinci', 'realism', 82);
insert into Artist (artistID, name, biography, style, totalExhibitions) values (8, 'Briney Dyos', 'Pablo Picasso', 'realism', 62);
insert into Artist (artistID, name, biography, style, totalExhibitions) values (9, 'Malissia Krugmann', 'Frida Kahlo', 'impressionism', 6);
insert into Artist (artistID, name, biography, style, totalExhibitions) values (10, 'Rebbecca Prebble', 'Leonardo da Vinci', 'abstract', 87);
insert into Artist (artistID, name, biography, style, totalExhibitions) values (11, 'Ladonna Tills', 'Michelangelo', 'impressionism', 41);
insert into Artist (artistID, name, biography, style, totalExhibitions) values (12, 'Rasla Sartain', 'Pablo Picasso', 'abstract', 12);
insert into Artist (artistID, name, biography, style, totalExhibitions) values (13, 'Micheline Danskine', 'Vincent van Gogh', 'realism', 84);
insert into Artist (artistID, name, biography, style, totalExhibitions) values (14, 'Creigh Pennone', 'Michelangelo', 'abstract', 32);
insert into Artist (artistID, name, biography, style, totalExhibitions) values (15, 'Phoebe Bows', 'Leonardo da Vinci', 'abstract', 1);
insert into Artist (artistID, name, biography, style, totalExhibitions) values (16, 'Minny Northleigh', 'Vincent van Gogh', 'realism', 85);
insert into Artist (artistID, name, biography, style, totalExhibitions) values (17, 'Laureen Eagell', 'Leonardo da Vinci', 'realism', 62);
insert into Artist (artistID, name, biography, style, totalExhibitions) values (18, 'Rowland Champion', 'Pablo Picasso', 'abstract', 100);
insert into Artist (artistID, name, biography, style, totalExhibitions) values (19, 'Margalit Glander', 'Frida Kahlo', 'realism', 32);
insert into Artist (artistID, name, biography, style, totalExhibitions) values (20, 'Carlie Ishchenko', 'Leonardo da Vinci', 'impressionism', 25);
insert into Artist (artistID, name, biography, style, totalExhibitions) values (21, 'Gusella Alvy', 'Frida Kahlo', 'realism', 66);
insert into Artist (artistID, name, biography, style, totalExhibitions) values (22, 'Chevalier Jandl', 'Vincent van Gogh', 'realism', 63);
insert into Artist (artistID, name, biography, style, totalExhibitions) values (23, 'Bridget Bernadzki', 'Leonardo da Vinci', 'realism', 5);
insert into Artist (artistID, name, biography, style, totalExhibitions) values (24, 'Mylo Lukash', 'Michelangelo', 'realism', 56);
insert into Artist (artistID, name, biography, style, totalExhibitions) values (25, 'Henrie O''Fihillie', 'Pablo Picasso', 'impressionism', 1);
insert into Artist (artistID, name, biography, style, totalExhibitions) values (26, 'Hermy MacCague', 'Vincent van Gogh', 'realism', 9);
insert into Artist (artistID, name, biography, style, totalExhibitions) values (27, 'Madelaine Perillo', 'Frida Kahlo', 'impressionism', 71);
insert into Artist (artistID, name, biography, style, totalExhibitions) values (28, 'Kassandra Gobourn', 'Michelangelo', 'realism', 69);
insert into Artist (artistID, name, biography, style, totalExhibitions) values (29, 'Thedric Overington', 'Frida Kahlo', 'impressionism', 67);
insert into Artist (artistID, name, biography, style, totalExhibitions) values (30, 'Wolfgang Jantot', 'Vincent van Gogh', 'abstract', 69);
insert into Artist (artistID, name, biography, style, totalExhibitions) values (31, 'Sergeant Linturn', 'Pablo Picasso', 'impressionism', 10);
insert into Artist (artistID, name, biography, style, totalExhibitions) values (32, 'Codie Benezet', 'Pablo Picasso', 'impressionism', 3);
insert into Artist (artistID, name, biography, style, totalExhibitions) values (33, 'Fern Cappel', 'Pablo Picasso', 'abstract', 37);
insert into Artist (artistID, name, biography, style, totalExhibitions) values (34, 'Karole Mitham', 'Frida Kahlo', 'realism', 59);
insert into Artist (artistID, name, biography, style, totalExhibitions) values (35, 'Lacy Kuhle', 'Frida Kahlo', 'realism', 63);
insert into Artist (artistID, name, biography, style, totalExhibitions) values (36, 'Sharia Sleeford', 'Leonardo da Vinci', 'realism', 1);
insert into Artist (artistID, name, biography, style, totalExhibitions) values (37, 'Ragnar Weems', 'Leonardo da Vinci', 'realism', 24);
insert into Artist (artistID, name, biography, style, totalExhibitions) values (38, 'Clem Glennard', 'Michelangelo', 'impressionism', 18);
insert into Artist (artistID, name, biography, style, totalExhibitions) values (39, 'De witt Piddock', 'Pablo Picasso', 'realism', 39);
insert into Artist (artistID, name, biography, style, totalExhibitions) values (40, 'Giacopo De Fraine', 'Vincent van Gogh', 'abstract', 6);
insert into Artist (artistID, name, biography, style, totalExhibitions) values (41, 'Leonardo Pobjay', 'Vincent van Gogh', 'impressionism', 80);
insert into Artist (artistID, name, biography, style, totalExhibitions) values (42, 'Leo Kildale', 'Leonardo da Vinci', 'abstract', 65);
insert into Artist (artistID, name, biography, style, totalExhibitions) values (43, 'Cordelie O'' Mullan', 'Michelangelo', 'impressionism', 9);
insert into Artist (artistID, name, biography, style, totalExhibitions) values (44, 'Emmery Catenot', 'Michelangelo', 'realism', 79);
insert into Artist (artistID, name, biography, style, totalExhibitions) values (45, 'Bonnee Rospars', 'Vincent van Gogh', 'impressionism', 90);
insert into Artist (artistID, name, biography, style, totalExhibitions) values (46, 'Agathe Gelling', 'Michelangelo', 'impressionism', 28);
insert into Artist (artistID, name, biography, style, totalExhibitions) values (47, 'Temple Goold', 'Vincent van Gogh', 'realism', 75);
insert into Artist (artistID, name, biography, style, totalExhibitions) values (48, 'Walther Cluckie', 'Pablo Picasso', 'abstract', 20);
insert into Artist (artistID, name, biography, style, totalExhibitions) values (49, 'Penn Esser', 'Vincent van Gogh', 'realism', 79);
insert into Artist (artistID, name, biography, style, totalExhibitions) values (50, 'Kessiah Francisco', 'Leonardo da Vinci', 'abstract', 70);
insert into Artist (artistID, name, biography, style, totalExhibitions) values (51, 'Danya Laurenceau', 'Michelangelo', 'abstract', 78);
insert into Artist (artistID, name, biography, style, totalExhibitions) values (52, 'Meade McKinnell', 'Leonardo da Vinci', 'abstract', 67);
insert into Artist (artistID, name, biography, style, totalExhibitions) values (53, 'Willabella Vallerine', 'Vincent van Gogh', 'abstract', 21);
insert into Artist (artistID, name, biography, style, totalExhibitions) values (54, 'Cristian Bette', 'Pablo Picasso', 'abstract', 89);
insert into Artist (artistID, name, biography, style, totalExhibitions) values (55, 'Bearnard Truscott', 'Vincent van Gogh', 'impressionism', 46);
insert into Artist (artistID, name, biography, style, totalExhibitions) values (56, 'Joanna O''Grada', 'Vincent van Gogh', 'realism', 48);
insert into Artist (artistID, name, biography, style, totalExhibitions) values (57, 'Caresa Pleavin', 'Pablo Picasso', 'abstract', 66);
insert into Artist (artistID, name, biography, style, totalExhibitions) values (58, 'Shanan Rodda', 'Vincent van Gogh', 'realism', 58);
insert into Artist (artistID, name, biography, style, totalExhibitions) values (59, 'Christian Richie', 'Michelangelo', 'abstract', 18);
insert into Artist (artistID, name, biography, style, totalExhibitions) values (60, 'Lyndsay Carayol', 'Leonardo da Vinci', 'impressionism', 22);
insert into Artist (artistID, name, biography, style, totalExhibitions) values (61, 'Saw Whilde', 'Pablo Picasso', 'impressionism', 12);
insert into Artist (artistID, name, biography, style, totalExhibitions) values (62, 'Cam Gilbeart', 'Vincent van Gogh', 'impressionism', 52);
insert into Artist (artistID, name, biography, style, totalExhibitions) values (63, 'Scott Chad', 'Frida Kahlo', 'impressionism', 38);
insert into Artist (artistID, name, biography, style, totalExhibitions) values (64, 'Ceil Brearty', 'Michelangelo', 'realism', 90);
insert into Artist (artistID, name, biography, style, totalExhibitions) values (65, 'Humphrey Bradlaugh', 'Frida Kahlo', 'realism', 90);
insert into Artist (artistID, name, biography, style, totalExhibitions) values (66, 'Collin Courson', 'Michelangelo', 'realism', 13);
insert into Artist (artistID, name, biography, style, totalExhibitions) values (67, 'Roxanna Hamner', 'Pablo Picasso', 'abstract', 91);
insert into Artist (artistID, name, biography, style, totalExhibitions) values (68, 'Bronnie Healing', 'Vincent van Gogh', 'abstract', 30);
insert into Artist (artistID, name, biography, style, totalExhibitions) values (69, 'Nisse Hayle', 'Michelangelo', 'impressionism', 86);
insert into Artist (artistID, name, biography, style, totalExhibitions) values (70, 'Florian Kilpin', 'Michelangelo', 'realism', 83);
insert into Artist (artistID, name, biography, style, totalExhibitions) values (71, 'Egan Cariss', 'Michelangelo', 'abstract', 52);
insert into Artist (artistID, name, biography, style, totalExhibitions) values (72, 'Leonidas Philips', 'Frida Kahlo', 'realism', 19);
insert into Artist (artistID, name, biography, style, totalExhibitions) values (73, 'Randy Sidlow', 'Leonardo da Vinci', 'abstract', 24);
insert into Artist (artistID, name, biography, style, totalExhibitions) values (74, 'Rebeca Venable', 'Vincent van Gogh', 'realism', 87);
insert into Artist (artistID, name, biography, style, totalExhibitions) values (75, 'Hart Klempke', 'Vincent van Gogh', 'abstract', 72);
insert into Artist (artistID, name, biography, style, totalExhibitions) values (76, 'Brinna Lodder', 'Vincent van Gogh', 'abstract', 74);
insert into Artist (artistID, name, biography, style, totalExhibitions) values (77, 'Isaiah Ahrens', 'Michelangelo', 'realism', 29);
insert into Artist (artistID, name, biography, style, totalExhibitions) values (78, 'Nixie Dmitrichenko', 'Vincent van Gogh', 'realism', 4);
insert into Artist (artistID, name, biography, style, totalExhibitions) values (79, 'Myca Gwilliams', 'Pablo Picasso', 'abstract', 56);
insert into Artist (artistID, name, biography, style, totalExhibitions) values (80, 'Olag O''Fairy', 'Vincent van Gogh', 'realism', 37);
insert into Artist (artistID, name, biography, style, totalExhibitions) values (81, 'Zena Brasseur', 'Michelangelo', 'impressionism', 87);
insert into Artist (artistID, name, biography, style, totalExhibitions) values (82, 'Carey Joust', 'Vincent van Gogh', 'realism', 73);
insert into Artist (artistID, name, biography, style, totalExhibitions) values (83, 'Marchall Tames', 'Frida Kahlo', 'impressionism', 19);
insert into Artist (artistID, name, biography, style, totalExhibitions) values (84, 'Adella Fragino', 'Pablo Picasso', 'abstract', 68);
insert into Artist (artistID, name, biography, style, totalExhibitions) values (85, 'Coleen Jerson', 'Vincent van Gogh', 'realism', 95);
insert into Artist (artistID, name, biography, style, totalExhibitions) values (86, 'Emanuel Simchenko', 'Leonardo da Vinci', 'realism', 58);
insert into Artist (artistID, name, biography, style, totalExhibitions) values (87, 'Viola Jaye', 'Michelangelo', 'realism', 24);
insert into Artist (artistID, name, biography, style, totalExhibitions) values (88, 'Charlena Varfolomeev', 'Vincent van Gogh', 'impressionism', 16);
insert into Artist (artistID, name, biography, style, totalExhibitions) values (89, 'Eden Clynter', 'Leonardo da Vinci', 'realism', 4);
insert into Artist (artistID, name, biography, style, totalExhibitions) values (90, 'Naomi Tainton', 'Leonardo da Vinci', 'abstract', 82);
insert into Artist (artistID, name, biography, style, totalExhibitions) values (91, 'Bat O''Hannay', 'Frida Kahlo', 'impressionism', 11);
insert into Artist (artistID, name, biography, style, totalExhibitions) values (92, 'Raimondo Ambrose', 'Michelangelo', 'realism', 90);
insert into Artist (artistID, name, biography, style, totalExhibitions) values (93, 'Ray Streetfield', 'Michelangelo', 'impressionism', 56);
insert into Artist (artistID, name, biography, style, totalExhibitions) values (94, 'Bobbie Alfonzo', 'Vincent van Gogh', 'abstract', 39);
insert into Artist (artistID, name, biography, style, totalExhibitions) values (95, 'Herrick MacCallum', 'Michelangelo', 'abstract', 82);
insert into Artist (artistID, name, biography, style, totalExhibitions) values (96, 'Glynnis Busen', 'Leonardo da Vinci', 'impressionism', 78);
insert into Artist (artistID, name, biography, style, totalExhibitions) values (97, 'Mufi Proud', 'Vincent van Gogh', 'impressionism', 46);
insert into Artist (artistID, name, biography, style, totalExhibitions) values (98, 'Felicdad Woolis', 'Michelangelo', 'realism', 5);
insert into Artist (artistID, name, biography, style, totalExhibitions) values (99, 'Aloysius Noriega', 'Vincent van Gogh', 'realism', 18);
insert into Artist (artistID, name, biography, style, totalExhibitions) values (100, 'Talbert Cours', 'Michelangelo', 'abstract', 88);
