insert into gallery (galleryID, galleryName, location, contactDetails) values (1, 'Pagac LLC', '443 Dryden Point', 'tgoater0@1688.com');
insert into gallery (galleryID, galleryName, location, contactDetails) values (2, 'Predovic-Ebert', '13078 Dapin Plaza', 'tbruyntjes1@npr.org');
insert into gallery (galleryID, galleryName, location, contactDetails) values (3, 'Baumbach and Sons', '4 Hoard Terrace', 'apiegrome2@bizjournals.com');
insert into gallery (galleryID, galleryName, location, contactDetails) values (4, 'Runolfsdottir-Zemlak', '33 Amoth Terrace', 'gnix3@fema.gov');
insert into gallery (galleryID, galleryName, location, contactDetails) values (5, 'Kohler Group', '8 6th Crossing', 'aabbets4@facebook.com');
insert into gallery (galleryID, galleryName, location, contactDetails) values (6, 'Homenick LLC', '82325 Bunting Hill', 'smcmurty5@umich.edu');
insert into gallery (galleryID, galleryName, location, contactDetails) values (7, 'Kirlin and Sons', '898 Bunker Hill Trail', 'bsamsin6@comsenz.com');
insert into gallery (galleryID, galleryName, location, contactDetails) values (8, 'Reinger Group', '63306 Cambridge Park', 'hstilgoe7@utexas.edu');
insert into gallery (galleryID, galleryName, location, contactDetails) values (9, 'Nolan-Kunde', '55322 2nd Terrace', 'irolfo8@weather.com');
insert into gallery (galleryID, galleryName, location, contactDetails) values (10, 'Bauch-Nicolas', '14286 Crescent Oaks Park', 'msnalum9@constantcontact.com');
insert into gallery (galleryID, galleryName, location, contactDetails) values (11, 'Rogahn, Heaney and Flatley', '47 Lawn Parkway', 'mgeggusa@istockphoto.com');
insert into gallery (galleryID, galleryName, location, contactDetails) values (12, 'Cronin-Kemmer', '298 Lotheville Point', 'ballpressb@army.mil');
insert into gallery (galleryID, galleryName, location, contactDetails) values (13, 'Wolf-Bauch', '3493 Clemons Drive', 'sduffiec@google.de');
insert into gallery (galleryID, galleryName, location, contactDetails) values (14, 'D''Amore Inc', '872 Riverside Hill', 'aslaneyd@bizjournals.com');
insert into gallery (galleryID, galleryName, location, contactDetails) values (15, 'Hettinger-Stark', '53 Arrowood Parkway', 'caddesse@ning.com');
insert into gallery (galleryID, galleryName, location, contactDetails) values (16, 'Nienow, Krajcik and Thiel', '413 Pankratz Terrace', 'fowensf@biblegateway.com');
insert into gallery (galleryID, galleryName, location, contactDetails) values (17, 'Rolfson LLC', '179 Loomis Plaza', 'sopenshawg@creativecommons.org');
insert into gallery (galleryID, galleryName, location, contactDetails) values (18, 'Stanton, Schmidt and Smith', '08 East Plaza', 'lharmanh@nps.gov');
insert into gallery (galleryID, galleryName, location, contactDetails) values (19, 'Herzog, Gerhold and O''Keefe', '81371 Ohio Circle', 'santoniazzii@unc.edu');
insert into gallery (galleryID, galleryName, location, contactDetails) values (20, 'Lueilwitz, Beer and O''Hara', '6984 Lerdahl Center', 'rpatenj@yandex.ru');
